language: scala
os: linux

before_install:
  - git fetch --tags

stages:
  - name: tests
    if: tag IS NOT present

jobs:
  include:
    - stage: tests
      name: "Scalafmt"
      script: sbt "all scalafmtCheckAll scalafmtSbtCheck"
    - name: "Scalafix"
      script: sbt "scalafixAll --check"
    - name: "Tests"
      script: sbt test

cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete