language: scala
os: linux
jdk: openjdk8

before_install:
  - git fetch --tags

stages:
  - name: tests
    if: tag IS NOT present
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

jobs:
  include:
    - stage: tests
      name: "Scalafmt"
      script: sbt "all scalafmtCheckAll scalafmtSbtCheck"
    - name: "Scalafix"
      script: sbt "scalafixAll --check"
    - name: "Tests"
      script: sbt test
    - stage: release
      name: "Release to Sonatype and update files"
      env: RELEASE="true"
      script: sbt headerCreateAll mdoc
      before_deploy: mv target/mdoc/* .
      deploy:
        provider: pages:git
        commit_message: Update markdown files and add missing headers
        edge: true
        token: $GITHUB_PERSONAL_ACCESS_TOKEN
        committer_from_gh: true
        target_branch: master
        on:
          branch: master

cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete